// <auto-generated />
namespace Infrastructure.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class duong_04072018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(duong_04072018));
        
        string IMigrationMetadata.Id
        {
            get { return "201807040612445_duong_04072018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
